# Generated by Django 5.1.7 on 2025-03-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogger_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter your bio details here.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
