name: Create Superuser
on: [workflow_dispatch]  # Manually trigger the action

jobs:
  run_django_command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Django Createsuperuser Command
        run: |
          python manage.py shell <<EOF
          from django.contrib.auth import get_user_model
          User = get_user_model()
          if not User.objects.filter(username='admin').exists():
              User.objects.create_superuser('admin', 'admin@example.com', 'admin12')
          print("Superuser created successfully!")
          EOF
